version: '3.8'

services:
  app:
    build:
      context: .       # Path to the Dockerfile
    container_name: java_app
    depends_on:
      - mongodb        # Ensure MongoDB starts before the app
    ports:
      - "8080:8080"    # Map your application's port
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
